python: can't open file '/mnt1/wumingyan/lixinze/Data/dpo_train/Search-o1/scripts/scripts/run_direct_gen.py': [Errno 2] No such file or directory
python: can't open file '/mnt1/wumingyan/lixinze/Data/dpo_train/Search-o1/scripts/scripts/run_direct_gen.py': [Errno 2] No such file or directory
python: can't open file '/mnt1/wumingyan/lixinze/Data/dpo_train/Search-o1/scripts/scripts/run_direct_gen.py': [Errno 2] No such file or directory
